# 1. CONFIGURACIÓN DE SPRING BOOT
spring.config.import=optional:configserver:,optional:file:.env[.properties]

# 2. CONEXIÓN A BASE DE DATOS LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=false

# 3. CREDENCIALES API GESTOPAGO (SANDBOX)
gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=${GESTOPAGO_AUTH_PASSWORD}
gestopago.auth.api-key=${GESTOPAGO_API_KEY}

# Redis y caché
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.cache.redis.time-to-live=600000

# INTEGRACION DE PRODUCTOS GESTOPAGO
gestopago.products.url=${gestopago.auth.url}
spring.cloud.openfeign.client.config.gestoPagoProducts.connectTimeout=5000
spring.cloud.openfeign.client.config.gestoPagoProducts.readTimeout=10000
spring.cloud.openfeign.client.config.gestoPagoXmlProducts.connectTimeout=5000
spring.cloud.openfeign.client.config.gestoPagoXmlProducts.readTimeout=10000